### ISSUE TITLE
ModuleNotFoundError: No module named 'ibm_noise_models'

### ISSUE THREAD

**Issue by beatakubiak** [ycchen1989/FederatedQLSTM#2]
I got the below message when I tried to run the code from the file lstm_base_class.py.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 37
     34 import qiskit.providers.aer.noise as noise
     36 # Custom qiskit noise model
---> 37 from ibm_noise_models import thermal_noise_backend, combined_error_noisy_backend, combined_noise_backend_normdist
     40 # Dataset
     41 # from generate_lstm_dataset import get_sine_data
     42 # from data.load_air_passengers import get_air_passenger_data_single_predict
     43 # from data.damped_shm import get_damped_shm_data
     44 from data.bessel_functions import get_bessel_data

ModuleNotFoundError: No module named 'ibm_noise_models'

**Comment by ycchen1989** [comment]
Please ignore all ibm stuffs here. We DON NOT use any qiskit stuffs here NOR consider any noise model.
