### ISSUE TITLE
TypeError: sigmoid(): argument 'input' (position 1) must be Tensor, not list

### ISSUE THREAD

**Issue by beatakubiak** [ycchen1989/FederatedQLSTM#3]
When I run the code from lstm_federated_time_series.py I get the following message.

I try to combine all the code in one Jupyter Notebook file. Now I am thinking that maybe some local variables become global, when I do it this way. Here is my file with the combined code.
[FederatedQLSTM-test1.zip](https://github.com/user-attachments/files/16566168/FederatedQLSTM-test1.zip)

TypeError                                 Traceback (most recent call last)
Cell In[59], line 322
    320 loss = 0
    321 for i in tqdm(range(num_selected)):
--> 322 	loss += client_update(client_models[i], opt[i], train_loader[client_idx[i]], epoch=epochs)
    324 losses_train.append((loss / num_selected))
    325 # server aggregate

Cell In[59], line 221, in client_update(client_model, optimizer, train_loader, epoch)
    213 print("BATCH IDX: ", batch_idx)
    214 # data, target = data.to(device), target.to(device)
    215 # optimizer.zero_grad()
    216 # output = client_model(data)
   (...)
    219 # loss = F.nll_loss(output, target)
    220 # loss = criterion(output, target)
--> 221 loss = MSEcost(VQC = client_model, X = data, Y = target, h_0 = h_0, c_0 = c_0, seq_len = 4)
    222 print("Loss: ", loss)
    223 loss.backward()

Cell In[59], line 44, in MSEcost(VQC, X, Y, h_0, c_0, seq_len)
     41 # predictions = torch.stack([variational_classifier(var_Q_circuit = var_Q_circuit, var_Q_bias = var_Q_bias, angles=item) for item in X])
     43 loss = nn.MSELoss()
---> 44 output = loss(torch.stack([VQC.forward(vec.reshape(seq_len,1), h_0, c_0).reshape(1,) for vec in X]), Y.reshape(Y.shape[0],1))
     45 print("LOSS AVG: ",output)
     46 return output

Cell In[59], line 44, in <listcomp>(.0)
     41 # predictions = torch.stack([variational_classifier(var_Q_circuit = var_Q_circuit, var_Q_bias = var_Q_bias, angles=item) for item in X])
     43 loss = nn.MSELoss()
---> 44 output = loss(torch.stack([VQC.forward(vec.reshape(seq_len,1), h_0, c_0).reshape(1,) for vec in X]), Y.reshape(Y.shape[0],1))
     45 print("LOSS AVG: ",output)
     46 return output

Cell In[56], line 237, in VQLSTM.forward(self, input_sequence_x, initial_h, initial_c)
    234 c_history = [] 
    236 for item in input_sequence_x:
--> 237 	h, c, out = self._forward(item, h, c)
    238 	h_history.append(h)
    239 	c_history.append(c)

Cell In[56], line 196, in VQLSTM._forward(self, single_item_x, single_item_h, single_item_c)
    194 res_from_cell_1 = self.cell_1.forward(res_temp)
    195 act_1 = nn.Sigmoid()
--> 196 res_from_cell_1 = act_1(res_from_cell_1)
    197 # print("res_from_cell_1: ", res_from_cell_1)
    198 res_from_cell_2 = self.cell_2.forward(res_temp)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
   1530     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1531 else:
-> 1532     return self._call_impl(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py:1541, in Module._call_impl(self, *args, **kwargs)
   1536 # If we don't have any hooks, we want to skip the rest of the logic in
   1537 # this function, and just call forward.
   1538 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1539         or _global_backward_pre_hooks or _global_backward_hooks
   1540         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1541     return forward_call(*args, **kwargs)
   1543 try:
   1544     result = None

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\activation.py:292, in Sigmoid.forward(self, input)
    291 def forward(self, input: Tensor) -> Tensor:
--> 292     return torch.sigmoid(input)

TypeError: sigmoid(): argument 'input' (position 1) must be Tensor, not list

**Comment by ycchen1989** [comment]
try not to use jupyter notebooks.

**Comment by ycchen1989** [comment]
BTW, which versions of PyTorch and PennyLane did you use?

**Comment by ycchen1989** [comment]
Is it possible for you to run the original codes on your virtual env or conda env?

**Comment by beatakubiak** [comment]
> BTW, which versions of PyTorch and PennyLane did you use?

import torch
print(torch.__version__)
2.3.0+cpu

import pennylane as qml
print(qml.__version__)
0.35.1

**Comment by beatakubiak** [comment]
> Is it possible for you to run the original codes on your virtual env or conda env?

I don't know. I will give it a try.

**Comment by ycchen1989** [comment]
Please try with:
pennylane==0.25.1
pytorch=1.10.1

**Comment by beatakubiak** [comment]
> Please try with: pennylane==0.25.1 pytorch=1.10.1

What version of python do you have for these versions of pennylane and pytorch?

When I tried to install pytorch 1.10.1 in my virtual env I got the following message. 
pip install pytorch==1.10.1
ERROR: Could not find a version that satisfies the requirement pytorch==1.10.1 (from versions: 0.1.2, 1.0.2)
ERROR: No matching distribution found for pytorch==1.10.1

I have read I need to downgrade to version 3.7.9 of python, which I did (in my new virtual environment).
While installing version 0.25.1 of pennylane I got the message:

ERROR: pennylane-lightning 0.37.0 has requirement pennylane>=0.36, but you'll have pennylane 0.25.1 which is incompatible.

**Comment by ycchen1989** [comment]
How about create a clean env and install from scratch?
I think py 3.7 or 3.9 should be fine.

**Comment by beatakubiak** [comment]
I needed 64-bit version of python. I went with python 3.7.9. I was able to run the code from jupyter notebook. Thank you for the help with this.
